Added data for Sem 1 2022-23
arpit-saxena/schedule-maker pull request #12
Opened 2022-08-02 17:44 UTC by Pratham-T

2022-08-02 18:02 UTC, arpit-saxena requested changes
Also add your name in https://github.com/arpit-saxena/schedule-maker/blob/master/AUTHORS.md

2022-08-02 18:02 UTC, arpit-saxena commented on docs/index.html
>              <p class="text-muted h4"> Made by Arpit Saxena | Current calendar contributed by <a href="https://github.com/DivyanshMittal-exe">Divyansh Mittal</a> | Find source code on <a href="https:/
Add your name here

2022-08-02 18:50 UTC, Pratham-T commented on docs/index.html
>              <p class="text-muted h4"> Made by Arpit Saxena | Current calendar contributed by <a href="https://github.com/DivyanshMittal-exe">Divyansh Mittal</a> | Find source code on <a href="https:/
Added.

2022-08-03 02:41 UTC, arpit-saxena approved these changes

2022-08-03 02:41 UTC, merged